"""Extra tools management for dynamically generated agent tools."""

import ast
import importlib.util
import sys
from pathlib import Path
from typing import Any, Callable

from app.config import settings


class ExtraToolsManager:
    """
    Manage dynamically created tools that agents generate.
    
    Tools are stored in extra_tools/{user_id}/ directory and can be:
    - Loaded at runtime
    - Executed in sandbox
    - Shared between sessions
    """

    def __init__(self, user_id: str) -> None:
        """Initialize manager for a user."""
        self.user_id = user_id
        self.tools_dir = settings.extra_tools_dir / user_id
        self.tools_dir.mkdir(parents=True, exist_ok=True)
        self._loaded_tools: dict[str, Callable] = {}

    def save_tool(
        self,
        name: str,
        code: str,
        description: str,
        parameters: dict[str, Any] | None = None,
    ) -> Path:
        """
        Save a new tool generated by the agent.
        
        Args:
            name: Tool name (must be valid Python identifier)
            code: Python code for the tool function
            description: Description of what the tool does
            parameters: Optional parameter schema
            
        Returns:
            Path to saved tool file
        """
        # Validate name
        if not name.isidentifier():
            raise ValueError(f"Invalid tool name: {name}")

        # Validate code syntax
        try:
            ast.parse(code)
        except SyntaxError as e:
            raise ValueError(f"Invalid Python syntax: {e}")

        # Create tool file
        tool_path = self.tools_dir / f"{name}.py"

        # Build tool content
        content = f'''"""
{description}

Auto-generated tool for user {self.user_id}
Parameters: {parameters if parameters else "None"}
"""

{code}

# Tool metadata
__tool_name__ = "{name}"
__tool_description__ = """{description}"""
__tool_parameters__ = {parameters!r}
'''

        tool_path.write_text(content, encoding='utf-8')

        # Also save metadata
        meta_path = self.tools_dir / f"{name}.json"
        import json
        meta_path.write_text(json.dumps({
            'name': name,
            'description': description,
            'parameters': parameters,
            'file': str(tool_path),
        }), encoding='utf-8')

        return tool_path

    def list_tools(self) -> list[dict[str, Any]]:
        """List all saved tools for the user."""
        tools = []
        for meta_file in self.tools_dir.glob("*.json"):
            try:
                import json
                meta = json.loads(meta_file.read_text())
                tools.append(meta)
            except Exception:
                continue
        return tools

    def load_tool(self, name: str) -> Callable | None:
        """
        Load a tool by name and return the callable.
        
        Args:
            name: Tool name
            
        Returns:
            The tool function or None if not found
        """
        if name in self._loaded_tools:
            return self._loaded_tools[name]

        tool_path = self.tools_dir / f"{name}.py"
        if not tool_path.exists():
            return None

        try:
            # Load module dynamically
            spec = importlib.util.spec_from_file_location(
                f"extra_tools.{self.user_id}.{name}",
                tool_path,
            )
            if spec is None or spec.loader is None:
                return None

            module = importlib.util.module_from_spec(spec)
            sys.modules[spec.name] = module
            spec.loader.exec_module(module)

            # Find the main function (same name as file)
            if hasattr(module, name):
                func = getattr(module, name)
                self._loaded_tools[name] = func
                return func

            # Or find first callable
            for attr_name in dir(module):
                if not attr_name.startswith('_'):
                    attr = getattr(module, attr_name)
                    if callable(attr) and not isinstance(attr, type):
                        self._loaded_tools[name] = attr
                        return attr

        except Exception as e:
            print(f"Error loading tool {name}: {e}")
            return None

        return None

    def delete_tool(self, name: str) -> bool:
        """Delete a saved tool."""
        tool_path = self.tools_dir / f"{name}.py"
        meta_path = self.tools_dir / f"{name}.json"

        deleted = False
        if tool_path.exists():
            tool_path.unlink()
            deleted = True
        if meta_path.exists():
            meta_path.unlink()
            deleted = True

        self._loaded_tools.pop(name, None)
        return deleted

    def get_tool_code(self, name: str) -> str | None:
        """Get the source code of a tool."""
        tool_path = self.tools_dir / f"{name}.py"
        if tool_path.exists():
            return tool_path.read_text(encoding='utf-8')
        return None

    async def execute_tool(
        self,
        name: str,
        args: dict[str, Any],
    ) -> Any:
        """
        Execute a tool with given arguments.
        
        Args:
            name: Tool name
            args: Arguments to pass to the tool
            
        Returns:
            Tool execution result
        """
        func = self.load_tool(name)
        if func is None:
            raise ValueError(f"Tool not found: {name}")

        import asyncio
        if asyncio.iscoroutinefunction(func):
            return await func(**args)
        else:
            return func(**args)


class CodeExecutor:
    """Execute Python code in a sandboxed environment."""

    def __init__(self, user_id: str) -> None:
        """Initialize executor for a user."""
        self.user_id = user_id
        self.workspace = settings.extra_tools_dir / user_id / "workspace"
        self.workspace.mkdir(parents=True, exist_ok=True)

    async def execute(
        self,
        code: str,
        timeout: float = 30.0,
        on_output: Callable[[str], None] | None = None,
    ) -> dict[str, Any]:
        """
        Execute Python code.
        
        Args:
            code: Python code to execute
            timeout: Maximum execution time
            on_output: Callback for output lines
            
        Returns:
            Execution result with stdout, stderr, success
        """
        import subprocess
        import tempfile

        # Write code to temp file
        code_file = self.workspace / "code.py"
        code_file.write_text(code, encoding='utf-8')

        result = {
            'success': False,
            'stdout': '',
            'stderr': '',
            'return_code': -1,
        }

        try:
            process = subprocess.Popen(
                [sys.executable, str(code_file)],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                cwd=str(self.workspace),
                text=True,
            )

            stdout_lines = []
            stderr_lines = []

            # Read output with timeout
            import asyncio
            try:
                stdout, stderr = await asyncio.wait_for(
                    asyncio.get_event_loop().run_in_executor(
                        None, process.communicate
                    ),
                    timeout=timeout,
                )
                result['stdout'] = stdout
                result['stderr'] = stderr
                result['return_code'] = process.returncode
                result['success'] = process.returncode == 0

                if on_output and stdout:
                    for line in stdout.splitlines():
                        on_output(line)

            except asyncio.TimeoutError:
                process.kill()
                result['stderr'] = f"Execution timed out after {timeout}s"
                result['return_code'] = -1

        except Exception as e:
            result['stderr'] = str(e)

        return result

    def cleanup(self) -> None:
        """Clean up workspace files."""
        import shutil
        if self.workspace.exists():
            for f in self.workspace.iterdir():
                if f.is_file():
                    f.unlink()
